apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sandboxed-containers-operator-by2i
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sandboxed-containers-operator-by2i
    app.kubernetes.io/part-of: sandboxed-containers-operator-1
  name: sandboxed-containers-operator-by2i
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: sandboxed-containers-operator-by2i
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sandboxed-containers-operator-by2i
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-dbox-containers-tenant/sandboxed-containers-operator-1/sandboxed-containers-operator-by2i@sha256:ff6d0bb0d4337d20dc1c3feb85d050d7f57c42a2fd6985f69bdfca3eb8029023
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
