apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sandboxed-containers-operator-by2i
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sandboxed-containers-operator-by2i
    app.kubernetes.io/part-of: sandboxed-containers-operator-1
  name: sandboxed-containers-opernvpn
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: sandboxed-containers-operator-by2i
    weight: 100
status: {}
